apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      s1:
        type: string
        default: hello world
        required: true
        description: a string
      n1:
        type: number
        default: 12
        description: a number
      c1:
        type: choice
        options:
          - a
          - b
          - c
        default: a
        description: a choice
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
