apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      s1:
        type: string
        default: hello world
        description: a string
      n1:
        type: number
        default: 12
        required: true
        description: a number
      c1:
        type: choice
        options:
          - a
          - b
          - c
        default: a
        required: true
        description: a choice
      b1:
        type: boolean
        default: true
        description: a boolean
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    needs:
      - app
  app:
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: 645a5a64-e80d-11ea-a794-42010a83ae1a
      disallowLaunchByUser: false
      instructions: ""
      approvalInputs: |
        {}
