apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      s1:
        type: string
      b1:
        type: boolean
      n1: 
        type: number
      c1: 
        type: choice
        options: 
          - a
          - b
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
