apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      s1:
        type: string
        default: hello world
        description: a string
      n1:
        type: number
        default: 12
        required: true
        description: a number
      c1:
        type: choice
        options:
          - a
          - b
          - c
        default: a
        description: a choice
      b1:
        type: boolean
        default: true
        description: a boolean
      s2:
        type: string
      s3:
        type: string
      s4:
        type: string
      s5:
        type: string
      s6:
        type: string
      s7:
        type: string
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
