apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: new automation
on:
  push:
    branches:
      - main
jobs:
  build:
    steps:
      - name: Say hello
      - name: Say hello
      - name: Say hello
      - name: Say hello
      - name: Say hello
  test1:
    steps:
      - name: Say hello
      - name: Say hello
  test2:
    steps:
      - name: Say hello
      - name: Say hello
    needs:
      - test1
      - build
